In [38]:
# Goal: figure out what topics received the most citations in a given year
import pandas as pd
import numpy as np

# Open the data
data_str = open('acm1st10000.txt',errors='ignore').read()
# data_str = open('C:\\Users\\Ryan\\Documents\\Ohio State\\8th Semester\\ECE 4194.02\\acm.txt', errors='ignore').read()
data_list = data_str.splitlines()

#for i in range(10):
 #   print(data_list[i])

# Create the dataframe
    # title: (string -- should be bag of words vector)
    # authors: (list)
    # year: publishing year (int)
    # venue: journal the paper was published in (string)
    # ind: numeric label/index of this paper (int)
    # ref_indces: identification index of the papers that referenced this paper (string)
    # abstract: (string -- should be bag of words vector ?)
names = ['title', 'authors', 'year', 'venue', 'ind', 'ref', 'abstract']
empty_row = pd.DataFrame(columns=names)
df = pd.DataFrame(columns=names)

i_df = 0
for i, val in enumerate(data_list):
    if not val:
        df = df.append(empty_row)
        i_df += 1
    if data_list[i].startswith('#*'):
        df.at[i_df,'title'] = val[2:]
    if data_list[i].startswith('#@'):
        df.at[i_df,'authors'] = val[2:]
    if data_list[i].startswith('#t'):
        df.at[i_df,'year'] = val[2:]
    if data_list[i].startswith('#c'):
        df.at[i_df,'venue'] = val[2:]
    if data_list[i].startswith('#index'):
        df.at[i_df,'ind'] = val[2:]
    if data_list[i].startswith('#%'):
        # If the data_list[i - 1] exists (necessary? Probably not)
            # If data_list[i - 1] didn't start with #%
                # Reset number of citations counter
        df.at[i_df,'ref'] = val[2:]
        # If i is not the end of the file
            # If data_list[i+1] doesn't start with #%:
                # Add the integer to the column
            # Else:
                # Increment the citation count
    if data_list[i].startswith('#!'):
        df.at[i_df,'abstract'] = val[2:]
    
print(df.head(5))
    
# T0-DO:
# -----------------------------------------------------------
# Force strings in dataframe that we want as ints to be ints
# Convert the strings in dataframe to bag of words vectors 
# Make a dataframe of just 2015 papers

# Account for no citations in a dataframe (if citation column is NaN, make it 0)
# Account for no abstract (if abstract column is NaN, remove the row completely)

                                               title  \
0  MOSFET table look-up models for circuit simula...   
1  The verification of the protection mechanisms ...   
2  Another view of functional and multivalued dep...   
3     Entity-relationship diagrams which are in BCNF   
4                          The computer comes of age   

                                             authors  year  \
0                                                NaN  1984   
1                                   Virgil D. Gligor  1984   
2                           M. Gyssens, J. Paredaens  1984   
3  Sushil Jajodia, Peter A. Ng, Frederick N. Spri...  1984   
4                                        Rene Moreau  1984   

                                           venue    ind  ref abstract  
0                  Integration, the VLSI Journal  ndex1  NaN      NaN  
1  International Journal of Parallel Programming  ndex2  NaN      NaN  
2  International Journal of Parallel Programming  ndex3  NaN      NaN  
3 

In [70]:
#print(df.head(5))
newdf=df.loc[df['year'] == '1986']
#print(newdf)
list_85_X=newdf['title'].tolist()
print(len(list_85))
#print(list)

5924


In [ ]:
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords

In [72]:
from sklearn.feature_extraction.text import CountVectorizer
stop_words_NLTK = set(stopwords.words('english')) 
vectorizer = CountVectorizer(stop_words=stop_words_NLTK, min_df=0.01, max_df=0.9, max_features=10)
X = vectorizer.fit_transform(list_85_X)
print(vectorizer.get_feature_names())
TrainingX=X.toarray()[0:len(X.toarray())-1]
TrainingY=
print(X.toarray())

['algorithm', 'analysis', 'computer', 'data', 'design', 'method', 'problem', 'problems', 'system', 'systems']
5924
[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
